name: snt_stable
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy
  - scipy
  - scikit-image
  - matplotlib
  - nibabel
  - pyqt
  - pip
  - pip:
      - itk-elastix
      - pyvista
      - pyvistaqt
      - pyigtl
